export const ADMIN_STEPONES_REQUEST = 'ADMIN_STEPONES_REQUEST'
export const ADMIN_STEPONES_SUCCESS = 'ADMIN_STEPONES_SUCCESS'
export const ADMIN_STEPONES_FAIL = 'ADMIN_STEPONES_FAIL'

export const ALL_STEPONES_REQUEST = 'ALL_STEPONES_REQUEST'
export const ALL_STEPONES_SUCCESS = 'ALL_STEPONES_SUCCESS'
export const ALL_STEPONES_FAIL = 'ALL_STEPONES_FAIL'

export const NEW_STEPONE_REQUEST = 'NEW_STEPONE_REQUEST'
export const NEW_STEPONE_SUCCESS = 'NEW_STEPONE_SUCCESS'
export const NEW_STEPONE_RESET = 'NEW_STEPONE_RESET'
export const NEW_STEPONE_FAIL = 'NEW_STEPONE_FAIL'

export const DELETE_STEPONE_REQUEST = 'DELETE_STEPONE_REQUEST'
export const DELETE_STEPONE_SUCCESS = 'DELETE_STEPONE_SUCCESS'
export const DELETE_STEPONE_RESET = 'DELETE_STEPONE_RESET'
export const DELETE_STEPONE_FAIL = 'DELETE_STEPONE_FAIL'

export const UPDATE_STEPONE_REQUEST = 'UPDATE_STEPONE_REQUEST'
export const UPDATE_STEPONE_SUCCESS = 'UPDATE_STEPONE_SUCCESS'
export const UPDATE_STEPONE_RESET = 'UPDATE_STEPONE_RESET'
export const UPDATE_STEPONE_FAIL = 'UPDATE_STEPONE_FAIL'

export const STEPONE_DETAILS_REQUEST = 'STEPONE_DETAILS_REQUEST'
export const STEPONE_DETAILS_SUCCESS = 'STEPONE_DETAILS_SUCCESS'
export const STEPONE_DETAILS_FAIL = 'STEPONE_DETAILS_FAIL'



export const CLEAR_ERRORS = 'CLEAR_ERRORS'