export const ADMIN_STEPTWOS_REQUEST = 'ADMIN_STEPTWOS_REQUEST'
export const ADMIN_STEPTWOS_SUCCESS = 'ADMIN_STEPTWOS_SUCCESS'
export const ADMIN_STEPTWOS_FAIL = 'ADMIN_STEPTWOS_FAIL'

export const ALL_STEPTWOS_REQUEST = 'ALL_STEPTWOS_REQUEST'
export const ALL_STEPTWOS_SUCCESS = 'ALL_STEPTWOS_SUCCESS'
export const ALL_STEPTWOS_FAIL = 'ALL_STEPTWOS_FAIL'

export const NEW_STEPTWO_REQUEST = 'NEW_STEPTWO_REQUEST'
export const NEW_STEPTWO_SUCCESS = 'NEW_STEPTWO_SUCCESS'
export const NEW_STEPTWO_RESET = 'NEW_STEPTWO_RESET'
export const NEW_STEPTWO_FAIL = 'NEW_STEPTWO_FAIL'

export const DELETE_STEPTWO_REQUEST = 'DELETE_STEPTWO_REQUEST'
export const DELETE_STEPTWO_SUCCESS = 'DELETE_STEPTWO_SUCCESS'
export const DELETE_STEPTWO_RESET = 'DELETE_STEPTWO_RESET'
export const DELETE_STEPTWO_FAIL = 'DELETE_STEPTWO_FAIL'

export const UPDATE_STEPTWO_REQUEST = 'UPDATE_STEPTWO_REQUEST'
export const UPDATE_STEPTWO_SUCCESS = 'UPDATE_STEPTWO_SUCCESS'
export const UPDATE_STEPTWO_RESET = 'UPDATE_STEPTWO_RESET'
export const UPDATE_STEPTWO_FAIL = 'UPDATE_STEPTWO_FAIL'

export const STEPTWO_DETAILS_REQUEST = 'STEPTWO_DETAILS_REQUEST'
export const STEPTWO_DETAILS_SUCCESS = 'STEPTWO_DETAILS_SUCCESS'
export const STEPTWO_DETAILS_FAIL = 'STEPTWO_DETAILS_FAIL'



export const CLEAR_ERRORS = 'CLEAR_ERRORS'