export const ADMIN_STEPTHREES_REQUEST = 'ADMIN_STEPTHREES_REQUEST'
export const ADMIN_STEPTHREES_SUCCESS = 'ADMIN_STEPTHREES_SUCCESS'
export const ADMIN_STEPTHREES_FAIL = 'ADMIN_STEPTHREES_FAIL'

export const ALL_STEPTHREES_REQUEST = 'ALL_STEPTHREES_REQUEST'
export const ALL_STEPTHREES_SUCCESS = 'ALL_STEPTHREES_SUCCESS'
export const ALL_STEPTHREES_FAIL = 'ALL_STEPTHREES_FAIL'

export const NEW_STEPTHREE_REQUEST = 'NEW_STEPTHREE_REQUEST'
export const NEW_STEPTHREE_SUCCESS = 'NEW_STEPTHREE_SUCCESS'
export const NEW_STEPTHREE_RESET = 'NEW_STEPTHREE_RESET'
export const NEW_STEPTHREE_FAIL = 'NEW_STEPTHREE_FAIL'

export const DELETE_STEPTHREE_REQUEST = 'DELETE_STEPTHREE_REQUEST'
export const DELETE_STEPTHREE_SUCCESS = 'DELETE_STEPTHREE_SUCCESS'
export const DELETE_STEPTHREE_RESET = 'DELETE_STEPTHREE_RESET'
export const DELETE_STEPTHREE_FAIL = 'DELETE_STEPTHREE_FAIL'

export const UPDATE_STEPTHREE_REQUEST = 'UPDATE_STEPTHREE_REQUEST'
export const UPDATE_STEPTHREE_SUCCESS = 'UPDATE_STEPTHREE_SUCCESS'
export const UPDATE_STEPTHREE_RESET = 'UPDATE_STEPTHREE_RESET'
export const UPDATE_STEPTHREE_FAIL = 'UPDATE_STEPTHREE_FAIL'

export const STEPTHREE_DETAILS_REQUEST = 'STEPTHREE_DETAILS_REQUEST'
export const STEPTHREE_DETAILS_SUCCESS = 'STEPTHREE_DETAILS_SUCCESS'
export const STEPTHREE_DETAILS_FAIL = 'STEPTHREE_DETAILS_FAIL'



export const CLEAR_ERRORS = 'CLEAR_ERRORS'